version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak_container
    ports:
      - "8008:8080"
    env_file:
      - .env
    command: [ "start-dev" ]

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    env_file:
      - .env


  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "6443:80"
    depends_on:
      - ldap
    restart: unless-stopped
